#!/bin/sh

SRC_DIR="~/.local/src"
mkdir -p ~/.local/ ~/.local/share ~/.config $SRC_DIR

source ./programs

aur_handler() {
    #cd /tmp
    #pwd
    #git clone "$i" && cd "$i"
    # Use PKGBUILDS    
}

git_handler() {
    echo "$i"
}

misc_install() {
    # Install vim-plug
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \ 
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
}

# /\[multilib\]/{  # match multilib
#   $!{       # (!)not the ($)last line
#     N       # append the next line
#     s/#//g  # remove all "#"s. 
#   }
# }
# Enable multilib repositories in /etc/pacman.conf
sed '/\[multilib\]/{$!N;s,#,,g}' <<<"#[multilib]
#Include = /etc/pacman.d/mirrorlist" /etc/pacman.conf > /etc/pacman.conf # Understand this; I must not use code of which I do not understand the purpose

pacman -Syu
pacman -S --needed "$DISTRO_REPO"

for i in $AUR; do
    aur_handler "$i"
done

misc_install
