#!/bin/sh

[[ -z "$EDITOR" ]] && EDITOR="nvim"
SRC_DIR="~/.local/src"
mkdir -p ~/.local/bin ~/.local/src ~/.local/share ~/.config $SRC_DIR

source ./programs

aur_handler() {
    cd /tmp
    pwd
    git clone "$i" && cd "$i"
    
}

git_handler() {
    echo "$i"
}

read -p "Uncomment the [multilib] section and any other desired repositories. [Press Return to continue]"
exec "$EDITOR" /etc/pacman.conf

pacman -Syu
pacman -S --needed "$DISTRO_REPO"

for i in $AUR; do
    aur_handler "$i"
done
