#!/bin/bash

# Fonts
#xset +fp /usr/share/fonts/envypn
#xset fp rehash
fc-cache -frv

# For keyboard
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
setxkbmap -option compose:ralt
setxkbmap -option caps:swapescape

# For audio
#start_jack &
pulseaudio -D

# Mount HDD
#udisksctl mount -b /dev/sdc1 &

# Automatically start some services
mpd "$XDG_CONFIG_HOME"/mpd/mpd.conf
mpdscribble

# For GUI 
xrdb -load "$XDG_CONFIG_HOME/X11/xresources"
sleep 1
xsetroot -solid "#1f1f1f"
dunst &
sxhkd &
dwmstatus &
exec dwm
