#!/bin/bash

# Fonts
fc-cache -frv

# For keyboard
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
setxkbmap -option compose:ralt
setxkbmap -option caps:swapescape

# For audio
pidof pulseaudio || pulseaudio -D

# Automatically start some services
pidof mpd || mpd "$XDG_CONFIG_HOME"/mpd/mpd.conf
pidof mpdscribble || mpdscribble

# For GUI 
picom -b
xrdb -load "$XDG_CONFIG_HOME"/X11/xresources/comfy-mod
hsetroot -tile ~/pic/bg/bmp/238.png
dunst &
sxhkd &
killall dwmblocks; dwmblocks &
exec dwm
