#!/bin/bash

# Fonts
#xset +fp /usr/share/fonts/envypn
#xset fp rehash
fc-cache -frv

# For keyboard
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
setxkbmap -option compose:ralt
setxkbmap -option caps:swapescape

# For audio
#start_jack &
pidof pulseaudio || pulseaudio -D
#pactl load-module module-echo-cancel aec_method=webrtc source_name=echocancel sink_name=echocancel1
#pacmd set-default-source echocancel
#pacmd set-default-sink echocancel1
#jack_control start &

picom -b

# Mount HDD
#udisksctl mount -b /dev/sdc1 &

# Automatically start some services
pidof mpd || mpd "$XDG_CONFIG_HOME"/mpd/mpd.conf
pidof mpdscribble || mpdscribble

# For GUI 
#xrdb -load "$XDG_CONFIG_HOME/X11/xresources"
xrdb -load "$XDG_CONFIG_HOME/X11/default.dark"
#hsetroot -solid "#1f1f1f"
#hsetroot -tile ~/pic/bg/bmp/234.png
#hsetroot -tile ~/pic/bg/bmp/93.png
#hsetroot -tile ~/pic/bg/bmp/97.png
#hsetroot -tile ~/pic/bg/bmp/370.png
hsetroot -tile ~/pic/bg/bmp/391.png
dunst &
sxhkd &
#killall dwmstatus; dwmstatus &
killall dwmblocks; dwmblocks &
exec dwm
#exec herbstluftwm
