directory: ~/aud
plugins: inline convert

item_fields:
    portable_artist: |
            albumartist_sort.replace()

aunique:
    keys: albumartist album
    disambiguators: albumtype year label catalognum albumdisambig releasegroupdisambig
    bracket: '[]'

paths: 
    default: %lower{%asciify{mus/artist/$albumartist/$original_year-$album/$track-$title}}
    singleton: %lower{%asciify{mus/artist/$artist/$title}}
    albumtype:soundtrack: %lower{%asciify{mus/st/$original_year-$album/$track-$title}}
    comp: %lower{%asciify{mus/comp/$original_year-$album%/$track-$title}}
#    default: %lower{%asciify{mus/artist/$albumartist_sort/$original_year-$album/$track-$title}}
#    singleton: %lower{%asciify{mus/artist/$artist/$title}}
#    albumtype:soundtrack: %lower{%asciify{mus/st/$original_year-$album/$track-$title}}
#    comp: %lower{%asciify{mus/comp/$original_year-$album%/$track-$title}}

replace:
    '[\\/]': '-'
    #'\.': _
    #',\s*': '-'
    #';\s*': '--'
    ',': '.'
    ';': '-'
    '[\x00-\x1f]': '-'
    '[\~@\#\$%\^!<>:\`"\;[]{}\|]': '-'
    '\*': '-'
    '\?': '.'
    '!': '.'
    '\&': '-'
    '=': '-'
    ':\s*': '-'
    "'": ''
    '\s+$': ''
    '^\s+': ''
    '\s': _
    '・': _
