directory: ~/aud

paths: 
    default: mus/artist/$albumartist_sort/$original_year~$album%aunique{}/$track~$title
    singleton: mus/artist/$artist/$title
    albumtype:soundtrack: mus/st/$original_year~$album/$track~$title
    comp: mus/comp/$original_year~$album%aunique{}/$track~$title

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '\s': '-'
