paths: 
    default: _beets/artist/$albumartist/$original_year~$album/$track~$title
    singleton: _beets/artist/$artist/$title
    comp: _beets/comp/$original_year~$album%aunique{}/$track~$title
    albumtype:soundtrack: _beets/st/$original_year~$album/$track~$title

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '\s': '-'
