# Append our default paths
appendpath () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

appendpath "$HOME/misc/bin"
appendpath "$HOME/doc/src/scripts"
export PATH

export XDG_CONFIG_HOME="$HOME/conf"
export XDG_CACHE_HOME="$HOME/misc/cache"
export XDG_DATA_HOME="$HOME/misc/data"
export XDG_RUNTIME_DIR="$HOME/misc/run"

# Set various environmental variables
##########

# General
export VISUAL="nvim"
export EDITOR="nvim"
export TERMINAL="st"

# ZSH
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=20000
export SAVEHIST=10000

# XDG Base Directory workarounds
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME"/android
export ANDROID_AVD_HOME="$XDG_DATA_HOME"/android/
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME"/android/
export ADB_VENDOR_KEY="$XDG_CONFIG_HOME"/android
export LESSHISTFILE=-
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export GOPATH="$XDG_DATA_HOME"/go
export XCOMPOSEFILE="$XDG_CONFIG_HOME/X11/xcompose"

# Miscellaneous
#export LS_COLORS="di=1;34"
export QT_IM_MODULE=ibus 
export XMODIFIERS=@im=ibus
export QT_QPA_PLATFORMTHEME=qt5ct

##########

# Aliases
alias xcp="xclip -selection clipboard"
alias startx='startx "$XDG_CONFIG_HOME/X11/xinitrc"'
alias :q='exit'
alias irssi='irssi --config $XDG_CONFIG_HOME/irssi/config'
alias grep='grep --color=auto'
alias pacman='pacman --color always'
alias yay='yay --color always'
alias please='sudo'
